# Generated by Django 4.2 on 2024-05-26 04:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0003_networkmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSliderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=None, upload_to='')),
                ('time', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
